AppBundle\Entity\Credentials:
    properties:
        login:
            - NotBlank: ~
            - Type: string
        password:
            - NotBlank: ~
            - Type: string

AppBundle\Entity\Relative:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: familyNumber
    properties:
        user:
            - NotBlank: ~
            - Valid: ~
        familyNumber:
            - NotBlank: ~

AppBundle\Entity\Trip:
    properties:
        name:
            - NotBlank: ~
            - Type: string
        

AppBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: login
    properties:
        firstname:
            - NotBlank: ~
            - Type: string
        lastname:
            - NotBlank: ~
            - Type: string
        email:
            - NotBlank: ~
            - Email: ~
        plainPassword:
            - NotBlank: { groups: [New, FullUpdate] }
            - Type: string
            - Length:
                min: 4
                max: 50

