app:
    resource: "@AppBundle/Controller/"
    type:     annotation
#Route pour le site
add_director:
    path:     /admin/add-director
    defaults: { _controller: AppBundle:AdminDirector:addDirector }

add_partener:
    path:     /admin/add-partener
    defaults: { _controller: AppBundle:AdminPartener:addPartener }

add_trip:
    path: /admin/add-trip
    defaults: { _controller: AppBundle:AdminTrip:addTrip }

block_user:
    path: /admin/block-user
    defaults: { _controller: AppBundle:AdminUser:blockUser }

create_director:
    path: /admin/create-director
    defaults: { _controller: AppBundle:AdminDirector:createDirector }

delete_actuality:
    path: /admin/delete-actuality
    defaults: { _controller: AppBundle:AdminTrip:deleteActuality }

delete_actuality_execute:
    path: /admin/delete-actuality/{id}
    defaults: { _controller: AppBundle:AdminTrip:deleteActualityExecute }

delete_comment:
    path: /admin/delete-comment
    defaults: { _controller: AppBundle:AdminTrip:deleteComment }

delete_comment_execute:
    path: /admin/delete-comment/{id}
    defaults: { _controller: AppBundle:AdminTrip:deleteCommentExecute }

delete_director:
    path: /admin/delete-director
    defaults: { _controller: AppBundle:AdminDirector:deleteDirector }

delete_picture:
    path: /admin/delete-picture
    defaults: { _controller: AppBundle:AdminTrip:deletePicture }

delete_picture_execute:
    path: /admin/delete-picture/{id}
    defaults: { _controller: AppBundle:AdminTrip:deletePictureExecute }

delete_trip:
    path: /admin/delete-trip
    defaults: { _controller: AppBundle:AdminTrip:deleteTrip }

get_picture:
    path: /admin/get-picture
    defaults: { _controller: AppBundle:AdminTrip:getPicture }

home:
    path: /admin/accueil
    defaults: {_controller: AppBundle:Admin:home}

import:
    path: /admin/import
    defaults: { _controller: AppBundle:AdminChild:import}

login:
    path:     login
    defaults: { _controller: AppBundle:Admin:login }

login_check:
    path: login_check

logout:
    path: logout

unblock_user:
    path: /admin/unblock-user
    defaults: { _controller: AppBundle:AdminUser:unblockUser }

upload_brochure:
    path: /admin/upload_brochure
    defaults: { _controller: AppBundle:AdminUpload:upload }
    
#Route pour l'api
access_children: 
    type:     rest
    resource: AppBundle\Controller\AccessChildController

actuality:
    type:     rest
    resource: AppBundle\Controller\ActualityController

auth_tokens: 
    type:     rest
    resource: AppBundle\Controller\AuthTokenController

comments:
    type:     rest
    resource: AppBundle\Controller\CommentController

like_actualities: 
    type:     rest
    resource: AppBundle\Controller\LikeActualityController

like_pictures: 
    type:     rest
    resource: AppBundle\Controller\LikePictureController

participate_trips: 
    type:     rest
    resource: AppBundle\Controller\ParticipateTripController

pictures: 
    type:     rest
    resource: AppBundle\Controller\PictureController

relatives: 
    type:     rest
    resource: AppBundle\Controller\RelativeController

trips: 
    type:     rest
    resource: AppBundle\Controller\TripController

users: 
    type:     rest
    resource: AppBundle\Controller\UserController


